export const mockPhrases = [
    { id: 1, phrase: "La vida es un eco: lo que envías, regresa; lo que das, recibes.", isFavorite: true },
    { id: 2, phrase: "No cuentes los días, haz que los días cuenten.", isFavorite: false },
    { id: 3, phrase: "A veces perderse es la mejor manera de encontrarse.", isFavorite: false },
    { id: 4, phrase: "No tengas miedo de ir lento, solo teme quedarte quieto.", isFavorite: false },
    { id: 5, phrase: "El éxito es la suma de pequeños esfuerzos repetidos cada día.", isFavorite: false },
    { id: 6, phrase: "Haz más de lo que te hace feliz.", isFavorite: false },
    { id: 7, phrase: "No busques el momento perfecto, haz el momento perfecto.", isFavorite: false },
    { id: 8, phrase: "La mejor inversión siempre será en ti mismo.", isFavorite: true },
    { id: 9, phrase: "No puedes controlar todo, pero sí cómo reaccionas a todo.", isFavorite: true },
    { id: 10, phrase: "La creatividad es la inteligencia divirtiéndose.", isFavorite: false },
    { id: 11, phrase: "El pasado es un recuerdo, el futuro un misterio, el presente un regalo.", isFavorite: false },
    { id: 12, phrase: "Rodéate de personas que te hagan crecer.", isFavorite: false },
    { id: 13, phrase: "Si puedes soñarlo, puedes hacerlo.", isFavorite: true },
];
